Conjur gate support

diff --git a/bin/start-nginx b/bin/start-nginx
--- a/bin/start-nginx
+++ b/bin/start-nginx
@@ -4,6 +4,30 @@ psmgr=/tmp/nginx-buildpack-wait
 rm -f $psmgr
 mkfifo $psmgr
 
+# Split out the Conjur URL
+if [ -z "$CONJUR_RESOURCE_URL" ]; then
+  echo "ERROR: CONJUR_RESOURCE_URL not set."
+  exit 1
+fi
+
+export CONJUR_RESOURCE_PATH=${CONJUR_RESOURCE_URL#*//*/}
+export CONJUR_LOCATION=${CONJUR_RESOURCE_URL#*//}
+export CONJUR_HOST=${CONJUR_LOCATION%%/*}
+echo "buildpack=nginx at=conjur-setup host=$CONJUR_HOST path=$CONJUR_RESOURCE_PATH"
+
+# Get the certificate
+echo | openssl s_client -showcerts -connect sandbox.conjur.um.pl.eu.org:443 2> /dev/null | openssl x509 > /tmp/conjur.pem
+export CONJUR_CERT_ACTUAL_FINGERPRINT=`openssl x509 -fingerprint -noout -in ../sandbox/conjur-sandbox.pem | sed -e s/.*=//`
+echo "buildpack=nginx at=conjur-ssl fingerprint=$CONJUR_CERT_ACTUAL_FINGERPRINT"
+
+# Verify the fingerprint
+if ! [ -z "$CONJUR_CERT_FINGERPRINT" ]; then
+  if ! [ "$CONJUR_CERT_ACTUAL_FINGERPRINT" == "$CONJUR_CERT_FINGERPRINT" ]; then
+    echo "ERROR: actual Conjur certificate fingerprint $CONJUR_CERT_ACTUAL_FINGERPRINT does not match CONJUR_CERT_FINGERPRINT=$CONJUR_CERT_FINGERPRINT"
+    exit 1
+  fi
+fi
+
 #Evaluate config to get $PORT
 erb config/nginx.conf.erb > config/nginx.conf
 
